Repository wecode-bootcamp-korea/37-2nd-yourhouse-frontend, pull requests merged in 2022-10, with the labels that each got.

#1 [37기 김지원] ADD:FOOTER 완성
  src/components/Footer/Footer.js
Labels: 완료

#3 [37기 양석문] Modify: Rebase 완료 Merge 요청
  public/data/data.json
  public/data/detailfeed.json
  public/images/profile.jpg
  src/pages/Detail/Detail.js
  src/pages/Detail/components/DetailComment.js
  src/pages/Detail/components/DetailFeed.js
  src/pages/Detail/components/DetailProfile.js
Labels: 수정 요청

#5 ADD : 로그인/회원가입 레이아웃 및 통신 완료 (리뷰 반영)
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/UserAuth.js
Labels: 멘토 리뷰 요청

#9 [37기 박영태] Add: 마이페이지 레이아웃 구현 완료
  public/data/mock.json
  public/data/profile.json
  public/images/chat.png
  public/images/coupon2.png
  public/images/facebook.png
  public/images/heart2.png
  public/images/interior.png
  public/images/interior3.png
  public/images/interior4.png
  public/images/interior5.png
  public/images/kakao-talk.png
  public/images/kakaostory.png
  public/images/kakaotalk.png
  public/images/link1.png
  public/images/living.png
  public/images/naverblog2.png
  public/images/next.png
  public/images/ribbon3.png
  public/images/room.png
  public/images/room1.png
  public/images/sample.png
  public/images/share.png
  public/images/user.png
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageContent/MyPageContent.js
  src/pages/MyPage/MyPageDropdown/MyPageDropdown.js
  src/pages/MyPage/Overlay/Overlay.js
Labels: 멘토 리뷰 요청

#7 [37기 장문정] 업로드 기능구현 페이지 작업 완료
  package-lock.json
  package.json
  public/data/sample.json
  public/data/searchProduct.json
  public/images/down-arrow.png
  public/images/reload.png
  public/images/trash-bin.png
  public/images/up-arrow.png
  src/pages/Upload/MakerModal.js
  src/pages/Upload/ProductList.js
  src/pages/Upload/Upload.js
  src/pages/Upload/UploadList.js
  src/pages/Upload/data/selectFilter.js
Labels: 멘토 리뷰 요청

#6 ADD: 리스트페이지 레이아웃 완료
  public/data/list.json
  public/data/mock.json
  public/images/blueheart.png
  public/images/man.png
  public/images/man1.png
  public/images/remove.png
  public/images/v2.png
  src/pages/List/Dropdown/Dropdown.js
  src/pages/List/List.js
  src/pages/List/ListFilter/ListButton/ListButton.js
  src/pages/List/ListFilter/ListFilter.js
  src/pages/List/ListImages/ListFollow/ListFollow.js
  src/pages/List/ListImages/ListHeartButton/ListCount/LIstCount.js
  src/pages/List/ListImages/ListHeartButton/ListHeartButton.js
  src/pages/List/ListImages/ListImages.js
Labels: 멘토 리뷰 요청

#11 [37기 박영태] Feature/follow UI
  public/data/follow.json
  src/Router.js
  src/pages/Follow/Follow.js
Labels: Conflict 해결 요청, 수정 요청, Rebase 요청
